version: '3'
services:
  geth:
    build:
      context: .
      dockerfile: DockerfileGeth
    restart: "no"
    expose:
      - "8545"
      - "8546"
    depends_on:
      - postgres
  postgres:
    build:
      context: .
      dockerfile: DockerfilePostgres
    restart: "no"
    expose:
      - "5432"
  explorer:
    build:
      context: .
      dockerfile: DockerfileExplorer
    restart: "no"
    tty: true
    environment:
      - DATABASE_URL=ecto://postgres:@postgres/explorer?ssl=false
      - ETHEREUM_JSONRPC_HTTP_URL=http://geth:8545
      - ETHEREUM_JSONRPC_WS_URL=ws://geth:8546 
    ports:
      - "4000:4000"
    depends_on:
      - postgres
